/**************************************************************
 * FILENAME:    Makefile	REF: MK_pseudo-ralph_V00_00_pseudo_ralph
 *
 * DESCRIPTION:
 *      Makefile for <ATTEMPT>: pseudo_ralph
 *
 * ENVIRONMENT:
 *      Windows 10 Home v1803 x64
 *      Visual Studio Code 1.41.1
 *           Extensions: ms-vscode-remote.remote-wsl
 *
 * VERSION:
 *      0.0.0.1
 *
 * AUTHOR(s):
 *      Kevin Colour
 *
 * DATES:
 *      Created:			Sat Jan 11 21:10:10 PST 2020
 *		Verified Execute:	NULL
 *
****************************************************************/
